### ISSUE TITLE
Make global variables less likely to interfere other project variables

### ISSUE THREAD

**Issue by alexerlandsson** [alexerlandsson/css-fadeshow#9]
Even with the "fs-" prefix, the global variables could potentially interfere with other variables used in a large project where the css-fadeshow is included. To avoid this, I need to look for a solution where it isn't possible or at least reduce the chances.

**Possible solutions:**

- Somehow wrap everything
- Create a sass map of the settings variables reducing the chance of a conflict

**Comment by alexerlandsson** [comment]
Example on how I could use Sass Map:

```scss
@function fs-settings($key) {
  @if map-has-key($fs-settings, $key) {
    @return map-get($fs-settings, $key);
  }

  @warn "Unknown `#{$key}` in $fs-settings.";
  @return null;
}

.example {
  color: fs-settings(color);
}
```
